### PR TITLE
Make `audio_file#convert` raise an exception on failure

### LINKED ISSUE #651: Add test that checks that `AudioFile#convert` doesn't return before the actual conversion is finished

### LINKED ISSUE #654: Make sure `AudioFile#convert` throws an exception if the underlying ffmpeg process didn't exit with status 0

### PR DESCRIPTION
**Pull request by chvp**
Fixes #654.
Fixes #651.

- [x] I've added tests relevant to my changes.

### CODE REVIEW

File: test/models/audio_file_test.rb [hunk 1]
```diff
@@ -15,6 +15,16 @@
 require 'test_helper'
 
 class AudioFileTest < ActiveSupport::TestCase
+  class ProcessStub
+    def initialize(success, exit_status)
+      @success = success
+      @exit_status = exit_status
+    end
+
+    def success? = @success
```
Comment (robbevp) [inline test/models/audio_file_test.rb:24]: Couldn't we simplify this to:
```suggestion
    def initialize(exit_status)
      @exit_status = exit_status
    end

    def success? = @exit_status == 0
```

**Review by robbevp — COMMENTED** [review]
One suggestion to simplify the test stub.

The tests are also failing, but this seems to be #297 - so running them again might fix this

**Review by robbevp — APPROVED** [review]
