### PR TITLE
Check ffmpeg version and recalculate ContentLengths

### LINKED ISSUE #175: Changing FFmpeg version should invalidate ContentLength cache
- [x] There are no similar issues reported yet

**Describe the bug**
Changes to the FFmpeg internals can change the encoded length of files, breaking clients depending on this length being correct (like the android app).

**To Reproduce**
Find two ffmpeg version that encode to different sizes with the same settings.

**Expected behavior**
The way to fix this is probably to parse out the FFmpeg version on startup. If we add an `ffmpeg_version` field to the ContentLength cache we can delete the entries that don't have a matching version.

Open question: Do we want to queue jobs for ContentLength creation for the AudioFile/CodecConversion combinations that don't have a matching ContentLength? This probably improves user experience, but queuing `|codec_conversion| * |audio_file|` conversion jobs isn't something we want to do on the regular 😬.

### PR DESCRIPTION
**Pull request by robbevp**
# Description
Fix #175
Supersedes #188

A different take on the issue of ffmpeg versions - the responsibility to trigger check is now clearly up to the person who deploys the application.
The version check is handled by a rake task `ffmpeg:check_version`. This checks whether the stored version (either a file supplied as an envitionment variables or `log/ffmpeg_version.txt`) still matches the current version, triggers a method if not. If the file cannot be found or read, we fallback to version 0.0.0.

There is also a helper provided: `ffmpeg:init`. This sets the current ffmpeg version to the supplied environment variable or to `log/ffmpeg_version.txt`

If the versions do not match we destroy all content lengths and recalculate them for each AudioFile that matches the condition in `config/application.rb`

# How Has This Been Tested?

- [x] I've added tests relevant to my changes

### CODE REVIEW

File: config/environments/test.rb [hunk 1]
```diff
@@ -47,9 +47,9 @@
   config.active_job.queue_adapter = :delayed_job
   Delayed::Worker.delay_jobs = false
 
-  # For tests we want to be the transcode cache expiry setting to remain
-  # the same, regardless of the configuration in application.rb
+  # For tests we want to be the these settings to remain the same, regardless of the configuration in application.rb
```
Comment (chvp) [inline config/environments/test.rb:50]:
```suggestion
  # For tests we want these settings to remain the same, regardless of the configuration in application.rb
```

**Review by chvp — CHANGES_REQUESTED** [review]

**Review by chvp — APPROVED** [review]
